/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package enterabinaria.GUI;

import enterabinaria.EnteraBinaria;
import java.util.ArrayList;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author david
 */
public class VentanaPrincipal extends javax.swing.JFrame {
    
    private int numVar;
    private int numRes;
    private EnteraBinaria EB;
    private DefaultTableModel modeloRestricciones;
    private boolean minProblem;
    

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpanVarRes = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtNumVar = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtNumRes = new javax.swing.JTextField();
        btnGenCampos = new javax.swing.JButton();
        jcomMinMax = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jpanDatosIn = new javax.swing.JScrollPane();
        jtblEntradaDatos = new javax.swing.JTable();
        btnSolucion = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtxtSolucion = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFocusCycleRoot(false);
        setSize(new java.awt.Dimension(700, 500));

        jLabel2.setText("Ingrese el numero de variables: ");

        txtNumVar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumVarActionPerformed(evt);
            }
        });

        jLabel3.setText("Ingrese el numero de restricciones: ");

        txtNumRes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumResActionPerformed(evt);
            }
        });

        btnGenCampos.setText("Generar Campos");
        btnGenCampos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenCamposActionPerformed(evt);
            }
        });

        jcomMinMax.setMaximumRowCount(2);
        jcomMinMax.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Minimizar", "Maximizar" }));
        jcomMinMax.setAlignmentX(350.0F);
        jcomMinMax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcomMinMaxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpanVarResLayout = new javax.swing.GroupLayout(jpanVarRes);
        jpanVarRes.setLayout(jpanVarResLayout);
        jpanVarResLayout.setHorizontalGroup(
            jpanVarResLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanVarResLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(txtNumVar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jpanVarResLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnGenCampos)
                    .addGroup(jpanVarResLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(txtNumRes, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jcomMinMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        jpanVarResLayout.setVerticalGroup(
            jpanVarResLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanVarResLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpanVarResLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNumVar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txtNumRes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcomMinMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(btnGenCampos))
        );

        jLabel1.setText("Solucion PL Entera Binaria");
        jLabel1.setAlignmentX(350.0F);

        jtblEntradaDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jpanDatosIn.setViewportView(jtblEntradaDatos);

        btnSolucion.setText("solucionar");
        btnSolucion.setAlignmentX(350.0F);
        btnSolucion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSolucionActionPerformed(evt);
            }
        });

        jtxtSolucion.setEditable(false);
        jtxtSolucion.setColumns(20);
        jtxtSolucion.setRows(5);
        jScrollPane1.setViewportView(jtxtSolucion);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jpanVarRes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jpanDatosIn, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(269, 269, 269)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(btnSolucion)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 537, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jpanVarRes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jpanDatosIn, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSolucion)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNumVarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumVarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumVarActionPerformed

    private void txtNumResActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumResActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumResActionPerformed

    private void btnGenCamposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenCamposActionPerformed
        // TODO add your handling code here:
        EB = new EnteraBinaria();
        this.numRes = Integer.valueOf(txtNumRes.getText());
        this.numVar = Integer.valueOf(txtNumVar.getText());
        this.minProblem = Boolean.parseBoolean(this.jcomMinMax.getSelectedItem().toString());
        crearTablaRestricciones(numVar, numRes);
        //System.out.println(this.numVar + " " + this.numRes + " " + this.minProblem);
    }//GEN-LAST:event_btnGenCamposActionPerformed

    private void jcomMinMaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcomMinMaxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcomMinMaxActionPerformed

    private void btnSolucionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSolucionActionPerformed
        // TODO add your handling code here:
        EB.setMinProblem(minProblem);
        EB.setNumRes(numRes);
        EB.setNumVar(numVar);
        String sol = EB.Solucionar(jtblEntradaDatos);
        this.jtxtSolucion.setText(sol);
        
    }//GEN-LAST:event_btnSolucionActionPerformed
    
    private void crearTablaRestricciones(int numVar, int numRes) {
        
        Object cabeza[] = new String[numVar + 3];
        cabeza[0] = (" ");
        for (int i = 1; i <= numVar; i++) {
            cabeza[i] = ("X" + i);
        }
        cabeza[numVar + 1] = (" ");
        cabeza[numVar + 2] = (" ");

        modeloRestricciones = new DefaultTableModel(cabeza, 0) {
            public boolean isCellEditable(int row, int column) {
                if (column == 0) {
                    return false;
                }
                if (row == 0 && column >= modeloRestricciones.getColumnCount() - 2) {
                    return false;
                }
                return true;
            }
        };
        
        this.jtblEntradaDatos.setModel(modeloRestricciones);
        String fila[] = new String[numVar + 3];
        for (int i = 0; i < numRes + 1; i++) {
            if (i == 0) {
                fila[0] = new String("     Z =");
            } else {
                fila[0] = new String("Rest. " + (i));
                fila[modeloRestricciones.getColumnCount() - 2] = "<=";
            }
            modeloRestricciones.addRow(fila);
        }
    }

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGenCampos;
    private javax.swing.JButton btnSolucion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> jcomMinMax;
    private javax.swing.JScrollPane jpanDatosIn;
    private javax.swing.JPanel jpanVarRes;
    private javax.swing.JTable jtblEntradaDatos;
    private javax.swing.JTextArea jtxtSolucion;
    private javax.swing.JTextField txtNumRes;
    private javax.swing.JTextField txtNumVar;
    // End of variables declaration//GEN-END:variables
}
